name: yggdrasil_demo
description: A demo app for Yggdrasil.
publish_to: "none"

version: 1.10.4

environment:
  sdk: ^3.2.0
  flutter: 3.16.0

dependencies:
  flutter:
    sdk: flutter
  yggdrasil:
    path: ../
  get_it: 7.6.4
  # Don't update due to the flutter_bloc in other repose.
  provider: 5.0.0
  dotted_border: 2.1.0
  mockito: 5.4.3
  package_info_plus: 4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
