name: yggdrasil_demo
description: A demo app for yggdrasil.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: 3.0.5
  flutter: 3.10.5

dependencies:
  flutter:
    sdk: flutter
  yggdrasil:
    path: ../
  get_it: 7.6.0
  provider: 6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  fh_lints:
    git:
      ref: master # to-branch-script-tag
      url: git@github.com:futurehomeno/pubdev_registry.git
      path: packages/fh_lints
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
