name: yggdrasil_demo
description: A demo app for Yggdrasil.
publish_to: 'none'

version: 1.4.0

environment:
  sdk: ^3.0.5
  flutter: 3.10.5

dependencies:
  flutter:
    sdk: flutter
  yggdrasil:
    path: ../
  get_it: 7.6.0
  provider: 6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
