name: yggdrasil_demo
description: A demo app for Yggdrasil.
publish_to: 'none'

version: 1.6.5+10

environment:
  sdk: ^3.0.5
  flutter: 3.10.5

dependencies:
  flutter:
    sdk: flutter
  yggdrasil:
    path: ../
  get_it: 7.6.0
  provider: 5.0.0
  mockito: 5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pubdev_registry:
    git:
      ref: tim/validators # to-branch-script-tag
      url: git@github.com:futurehomeno/pubdev_registry.git
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
