name: yggdrasil_demo
description: A demo app for Yggdrasil.
publish_to: 'none'

version: 1.2.1

environment:
  sdk: ^3.0.5
  flutter: 3.10.5

dependencies:
  flutter:
    sdk: flutter
  yggdrasil:
    path: ../
  get_it: 7.6.0
  provider: 6.0.5

dev_dependencies:
  mockito: 5.4.2
  flutter_test:
    sdk: flutter
  fh_lints:
    git:
      ref: master # to-branch-script-tag
      url: git@github.com:futurehomeno/pubdev_registry.git
      path: packages/fh_lints
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
