targets:
  $default:
    sources:
      exclude:
        - example/**
    builders:
      theme_tailor:
        options:
          themes:
            - consumerLight
            - consumerDark
            - professionalLight
            - professionalDark
