targets:
  $default:
    sources:
      exclude:
        - example/**
    builders:
      mockito|mockBuilder:
        generate_for:
          - lib/**.dart
      theme_tailor:
        options:
          themes:
            - consumerLight
            - consumerDark
            - professionalLight
            - professionalDark
