targets:
  $default:
    builders:
      theme_tailor:
        options:
          themes:
            - consumerLight
            - consumerDark
            - professionalLight
            - professionalDark
