workflows:
  pr-builder:
    name: PR builder
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      groups:
        - frontend
      flutter: 3.10.5
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:

      - name: Moving cloned repo
        working_directory: /Users/builder
        script: |
          cp -R clone app_files
          rm -rf clone/*
          mv app_files clone

      - name: Downloading flutter cli
        script: |
          pwd
          git clone git@github.com:futurehomeno/flutter-cli.git $CM_BUILD_DIR/cli
          cd $CM_BUILD_DIR/cli
          flutter pub get

      - name: Checking formatting
        working_directory: /Users/builder/clone/app_files
        script: dart $CM_BUILD_DIR/cli/futurehome.dart f || exit 1

      - name: Analyzing
        working_directory: /Users/builder/clone/app_files
        script: flutter analyze


  create-version:
    name: Create version
    instance_type: mac_mini_m1
    max_build_duration: 10
    environment:
      groups:
        - frontend
      flutter: 3.10.5
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Cloning pubdev_registry repo
        working_directory: /Users/builder
        script: |
          rm -rf clone/*
          git clone git@github.com:futurehomeno/yggdrasil.git $CM_BUILD_DIR/app_files
          cd $CM_BUILD_DIR/app_files
          git checkout $CM_BRANCH

      - name: Downloading flutter cli
        script: |
          git clone git@github.com:futurehomeno/flutter-cli.git $CM_BUILD_DIR/cli
          cd $CM_BUILD_DIR/cli
          flutter pub get

      - name: Creating version
        working_directory: /Users/builder/clone/app_files
        script: dart $CM_BUILD_DIR/cli/futurehome.dart ci cav -ai -uc || exit 1


  create-custom-version:
    name: Create version
    instance_type: mac_mini_m1
    max_build_duration: 10
    environment:
      groups:
        - frontend
      flutter: 3.10.5
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Cloning pubdev_registry repo
        working_directory: /Users/builder
        script: |
          rm -rf clone/*
          git clone git@github.com:futurehomeno/yggdrasil.git $CM_BUILD_DIR/app_files
          cd $CM_BUILD_DIR/app_files
          git checkout $CM_BRANCH

      - name: Downloading flutter cli
        script: |
          git clone git@github.com:futurehomeno/flutter-cli.git $CM_BUILD_DIR/cli
          cd $CM_BUILD_DIR/cli
          flutter pub get

      - name: Creating version
        working_directory: /Users/builder/clone/app_files
        script: dart $CM_BUILD_DIR/cli/futurehome.dart ci cav $VERSION -uc || exit 1


  test-tag:
    name: Test tag
    instance_type: mac_mini_m1

    scripts:
      - name: Tag test
        script: echo $CM_TAG


  android-release:
    name: Android release
    instance_type: mac_mini_m1
    max_build_duration: 30

    environment:
      groups:
        - frontend
      android_signing:
        - yggdrasil_keystore
      flutter: 3.10.5

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: '*'
          include: true
      cancel_previous_builds: true

    scripts:
      - name: Set up local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/example/android/local.properties"

      - name: Get Flutter packages
        working_directory: $CM_BUILD_DIR/example
        script: flutter packages pub get

      - name: Build AAB with Flutter
        working_directory: $CM_BUILD_DIR/example
        script: flutter build apk --release

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      scripts:
        - name: Send artifacts to github
          working_directory: $CM_BUILD_DIR/example
          script: |
            #!/bin/sh
  
            # Change these variables accordingly
            REPO="futurehomeno/yggdrasil"
            ARTIFACT_PATH="build/app/outputs/flutter-apk/app-release.apk"
            TAG="1.6.0+3"
            echo $CM_TAG
  
            # Create a new release
            RELEASE_RESPONSE=$(
              curl --data "{
                \"tag_name\": \"$TAG\", 
                \"name\": \"$TAG\",
                \"draft\": false, 
                \"prerelease\": false
              }" \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -X POST "https://api.github.com/repos/$REPO/releases"
            )
  
            echo $RELEASE_RESPONSE
  
            # Extract the upload URL from the release response
            UPLOAD_URL=$(echo $RELEASE_RESPONSE | jq -r .upload_url | sed -e "s/{?name,label}//")
  
            if [ -z "$UPLOAD_URL" ]; then
              echo "Failed to get upload URL"
              exit 1
            fi
  
            # Upload the artifact
            curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: $(file -b --mime-type $ARTIFACT_PATH)" \
              --data-binary "@$ARTIFACT_PATH" \
              "$UPLOAD_URL?name=$(basename $ARTIFACT_PATH)"
