flutter_ver: &flutter_ver 3.16.0
xcode_ver: &xcode_ver latest

workflows:
  pr-builder:
    name: PR builder
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      groups:
        - frontend
      flutter: *flutter_ver
      xcode: *xcode_ver
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Moving cloned repo
        working_directory: /Users/builder
        script: |
          cp -R clone app_files
          rm -rf clone/*
          mv app_files clone

      - name: Analyzing demo app
        working_directory: /Users/builder/clone/app_files/demo_app/
        script: flutter analyze

      - name: Analyzing yggdrasil
        working_directory: /Users/builder/clone/app_files/yggdrasil/
        script: flutter analyze

  create-version:
    name: Create version
    instance_type: mac_mini_m1
    max_build_duration: 10
    environment:
      groups:
        - frontend
      flutter: *flutter_ver
      xcode: *xcode_ver
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Cloning yggdrasil repo
        working_directory: /Users/builder
        script: |
          rm -rf clone/*
          git clone git@github.com:futurehomeno/yggdrasil.git $CM_BUILD_DIR/app_files
          cd $CM_BUILD_DIR/app_files
          git checkout $CM_BRANCH

      - name: Downloading ratatosk
        script: |
          git clone git@github.com:futurehomeno/ratatosk.git $CM_BUILD_DIR/ratatosk
          cd $CM_BUILD_DIR/ratatosk
          git checkout crytek/cm
          flutter pub get
          dart pub global activate --source path ./

      - name: Creating version
        working_directory: /Users/builder/clone/app_files
        script: rat release -y || exit 1

  create-custom-version:
    name: Create custom version (Only VM usage)
    instance_type: mac_mini_m1
    max_build_duration: 10
    environment:
      groups:
        - frontend
      flutter: *flutter_ver
      xcode: *xcode_ver
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Cloning yggdrasil repo
        working_directory: /Users/builder
        script: |
          rm -rf clone/*
          git clone git@github.com:futurehomeno/yggdrasil.git $CM_BUILD_DIR/app_files
          cd $CM_BUILD_DIR/app_files
          git checkout $CM_BRANCH

      - name: Downloading ratatosk
        script: |
          git clone git@github.com:futurehomeno/ratatosk.git $CM_BUILD_DIR/ratatosk
          cd $CM_BUILD_DIR/ratatosk
          git checkout crytek/cm
          flutter pub get
          dart pub global activate --source path ./

      - name: Creating version for package
        working_directory: /Users/builder/clone/app_files
        script: rat release -v $VERSION -y || exit 1

  release:
    name: Android & macOS release
    instance_type: mac_mini_m1
    max_build_duration: 30

    environment:
      node: v21.1.0
      npm: 9.6.6
      groups:
        - frontend
        - slack
      android_signing:
        - yggdrasil_keystore
      flutter: *flutter_ver

    triggering:
      events:
        - tag
      cancel_previous_builds: true

    scripts:
      - name: Downloading flutter cli
        script: |
          git clone git@github.com:futurehomeno/flutter-cli.git $CM_BUILD_DIR/cli
          cd $CM_BUILD_DIR/cli
          flutter pub get

      - name: Downloading ratatosk
        script: |
          git clone git@github.com:futurehomeno/ratatosk.git $CM_BUILD_DIR/ratatosk
          cd $CM_BUILD_DIR/ratatosk
          flutter pub get
          dart pub global activate --source path ./

      - name: Install appdmg
        script: npm install -g appdmg

      - name: Set up local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/demo_app/android/local.properties"

      - name: Get Flutter packages
        working_directory: $CM_BUILD_DIR/demo_app
        script: flutter packages pub get

      - name: Build Android apk with Flutter
        working_directory: $CM_BUILD_DIR/demo_app
        script: flutter build apk --release

      - name: Build macOS with Flutter
        working_directory: $CM_BUILD_DIR/demo_app
        script: flutter build macos --release

      - name: Create dmg for macos build
        working_directory: $CM_BUILD_DIR/demo_app/installers/dmg_creator
        script: appdmg ./config.json ./yggdrasil.dmg

    publishing:
      scripts:
        - name: Send artifacts to github
          working_directory: $CM_BUILD_DIR/demo_app
          script: |
            #!/bin/sh

            # Change these variables accordingly
            REPO="futurehomeno/yggdrasil"
            ANDROID_ARTIFACT_PATH="demo_app/build/app/outputs/flutter-apk/app-release.apk"
            MACOS_ARTIFACT_PATH="demo_app/installers/dmg_creator/yggdrasil.dmg"

            # Create a new release
            RELEASE_RESPONSE=$(
              curl --data "{
                \"tag_name\": \"$CM_TAG\", 
                \"name\": \"$CM_TAG\",
                \"draft\": false, 
                \"prerelease\": false
              }" \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -X POST "https://api.github.com/repos/$REPO/releases"
            )

            echo $RELEASE_RESPONSE

            # Extract the upload URL from the release response
            UPLOAD_URL=$(echo $RELEASE_RESPONSE | jq -r .upload_url | sed -e "s/{?name,label}//")

            if [ -z "$UPLOAD_URL" ]; then
              echo "Failed to get upload URL"
              exit 1
            fi

            # Upload the android artifact
            curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: $(file -b --mime-type $ANDROID_ARTIFACT_PATH)" \
              --data-binary "@$ANDROID_ARTIFACT_PATH" \
              "$UPLOAD_URL?name=$(basename $ANDROID_ARTIFACT_PATH)"

            # Upload the macos artifact
            curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: $(file -b --mime-type $MACOS_ARTIFACT_PATH)" \
              --data-binary "@$MACOS_ARTIFACT_PATH" \
              "$UPLOAD_URL?name=$(basename $MACOS_ARTIFACT_PATH)"

        - name: Sending message to Slack
          script: |
            changelog=$(rat changelog -f $CM_TAG -t $CM_TAG -r)

            curl --location $YGGDRASIL_SLACK_WEBHOOK \
            --header 'Content-Type: application/json' \
            --data '
              {
                "text": "New version of Yggdrasil! ['"$CM_TAG"']\nhttps://github.com/futurehomeno/yggdrasil/releases/tag/'"$CM_TAG"'",
                "attachments": [
                  {
                    "blocks": [
                      {
                          "type": "divider"
                      },
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "'"$changelog"'"
                        }
                      },
                      {
                          "type": "divider"
                      },
                      {
                        "type": "actions",
                        "block_id": "actionblock",
                        "elements": [
                          {
                            "type": "button",
                            "text": {
                              "type": "plain_text",
                              "text": "Mac dmg :computer:"
                            },
                            "style": "primary",
                            "url": "https://github.com/futurehomeno/yggdrasil/releases/download/'"$CM_TAG"'/yggdrasil.dmg"
                          },
                          {
                            "type": "button",
                            "text": {
                              "type": "plain_text",
                              "text": "Android apk :iphone:"
                            },
                            "style": "primary",
                            "url": "https://github.com/futurehomeno/yggdrasil/releases/download/'"$CM_TAG"'/app-release.apk"
                          },
                          {
                            "type": "button",
                            "text": {
                              "type": "plain_text",
                              "text": "Support :technologist:"
                            },
                            "style": "primary",
                            "url": "https://app.slack.com/client/T025ENQJR/D0235KBKX2B"
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            '
