name: yggdrasil

version: 0.0.1
publish_to: none

environment:
  sdk: ^3.0.5
  flutter: 3.10.5

dependencies:
  flutter:
    sdk: flutter
  theme_tailor_annotation: 
    git:
      ref: main
      url: git@github.com:futurehomeno/theme_tailor.git
      path: packages/theme_tailor_annotation
  flutter_svg: 2.0.7

dev_dependencies:
  # Run `flutter pub run build_runner build --delete-conflicting-outputs` in order to generate stuff.
  build_runner: 2.4.6
  fh_lints:
    git:
      ref: releases/1.3.71 # to-pubdev-reference-script-tag
      url: git@github.com:futurehomeno/pubdev_registry.git
      path: packages/fh_lints
  flutter_test:
    sdk: flutter
  theme_tailor:
    git:
      ref: main
      url: git@github.com:futurehomeno/theme_tailor.git
      path: packages/theme_tailor

flutter:
  uses-material-design: true
  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/dosis/Dosis-Bold.ttf
        - asset: assets/fonts/dosis/Dosis-ExtraBold.ttf
        - asset: assets/fonts/dosis/Dosis-ExtraLight.ttf
        - asset: assets/fonts/dosis/Dosis-Light.ttf
        - asset: assets/fonts/dosis/Dosis-Medium.ttf
        - asset: assets/fonts/dosis/Dosis-Regular.ttf
        - asset: assets/fonts/dosis/Dosis-SemiBold.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
        - asset: assets/fonts/open_sans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/open_sans/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
        - asset: assets/fonts/open_sans/OpenSans-LightItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Medium.ttf
        - asset: assets/fonts/open_sans/OpenSans-MediumItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/open_sans/OpenSans-SemiBoldItalic.ttf

    - family: WorkSans
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Black.ttf
        - asset: assets/fonts/work_sans/WorkSans-BlackItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Bold.ttf
        - asset: assets/fonts/work_sans/WorkSans-BoldItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraBold.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraLight.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraLightItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Italic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Light.ttf
        - asset: assets/fonts/work_sans/WorkSans-LightItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Medium.ttf
        - asset: assets/fonts/work_sans/WorkSans-MediumItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Regular.ttf
        - asset: assets/fonts/work_sans/WorkSans-SemiBold.ttf
        - asset: assets/fonts/work_sans/WorkSans-SemiBoldItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Thin.ttf
        - asset: assets/fonts/work_sans/WorkSans-ThinItalic.ttf
  assets:
    - assets/icons/old/alarm/
    - assets/icons/old/app_devices/
    - assets/icons/old/automation/
    - assets/icons/old/big/
    - assets/icons/old/building_type/
    - assets/icons/old/color_presets/
    - assets/icons/old/controls/barrier/
    - assets/icons/old/controls/chargepoint/
    - assets/icons/old/controls/climate/
    - assets/icons/old/controls/door_lock/
    - assets/icons/old/controls/shading/
    - assets/icons/old/controls/siren/
    - assets/icons/old/device_alarm/
    - assets/icons/old/device_subtype/
    - assets/icons/old/device_type/
    - assets/icons/old/dogs/
    - assets/icons/old/energy_group/
    - assets/icons/old/energy_optimization_settings/
    - assets/icons/old/energy_statistics/
    - assets/icons/old/fh_font/
    - assets/icons/old/functionality/
    - assets/icons/old/household_settings/
    - assets/icons/old/hub/
    - assets/icons/old/mdu/battery/
    - assets/icons/old/mdu/contact/
    - assets/icons/old/mdu/device/
    - assets/icons/old/mdu/logo/
    - assets/icons/old/mdu/other/
    - assets/icons/old/mdu/premise/
    - assets/icons/old/mdu/ring/
    - assets/icons/old/mdu/role/
    - assets/icons/old/mdu/site/
    - assets/icons/old/mdu/stamp/
    - assets/icons/old/mdu/symbol/
    - assets/icons/old/media/
    - assets/icons/old/modes/
    - assets/icons/old/notification_group/
    - assets/icons/old/playground/
    - assets/icons/old/profile_settings/
    - assets/icons/old/room/
    - assets/icons/old/security/
    - assets/icons/old/services/
    - assets/icons/old/services/device_modes/
    - assets/icons/old/settings/
    - assets/icons/old/shading/
    - assets/icons/old/shared/
    - assets/icons/old/siren_mode/
    - assets/icons/old/square_flags/
    - assets/icons/old/text/
    - assets/icons/old/timeline/
    - assets/icons/old/timeline/events/
    - assets/icons/old/user_verification/
    - assets/icons/old/widgets/app_bar/
    - assets/icons/old/widgets/bottom_nav/
    - assets/icons/old/widgets/forms/fh_search/
    - assets/icons/old/widgets/pickers/fh_circular_color_temperature_picker/
    - assets/icons/old/widgets/pickers/fh_circular_picker/
    - assets/icons/old/widgets/pickers/fh_simple_slider/
    - assets/icons/old/widgets/sliders/
    - assets/icons/old/zwave_inclusion/