name: yggdrasil

version: 0.0.1
publish_to: none

environment:
  sdk: ^3.0.5
  flutter: 3.10.5

dependencies:
  flutter:
    sdk: flutter
  theme_tailor_annotation: 
    git:
      ref: main
      url: git@github.com:futurehomeno/theme_tailor.git
      path: packages/theme_tailor_annotation
  flutter_svg: 2.0.7

dev_dependencies:
  # Run `flutter pub run build_runner build --delete-conflicting-outputs` in order to generate stuff.
  build_runner: 2.4.6
  fh_lints:
    git:
      ref: releases/1.3.71 # to-pubdev-reference-script-tag
      url: git@github.com:futurehomeno/pubdev_registry.git
      path: packages/fh_lints
  flutter_test:
    sdk: flutter
  theme_tailor:
    git:
      ref: main
      url: git@github.com:futurehomeno/theme_tailor.git
      path: packages/theme_tailor

flutter:
  uses-material-design: true
  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/dosis/Dosis-Bold.ttf
        - asset: assets/fonts/dosis/Dosis-ExtraBold.ttf
        - asset: assets/fonts/dosis/Dosis-ExtraLight.ttf
        - asset: assets/fonts/dosis/Dosis-Light.ttf
        - asset: assets/fonts/dosis/Dosis-Medium.ttf
        - asset: assets/fonts/dosis/Dosis-Regular.ttf
        - asset: assets/fonts/dosis/Dosis-SemiBold.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
        - asset: assets/fonts/open_sans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/open_sans/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
        - asset: assets/fonts/open_sans/OpenSans-LightItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Medium.ttf
        - asset: assets/fonts/open_sans/OpenSans-MediumItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/open_sans/OpenSans-SemiBoldItalic.ttf

    - family: WorkSans
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Black.ttf
        - asset: assets/fonts/work_sans/WorkSans-BlackItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Bold.ttf
        - asset: assets/fonts/work_sans/WorkSans-BoldItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraBold.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraLight.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraLightItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Italic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Light.ttf
        - asset: assets/fonts/work_sans/WorkSans-LightItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Medium.ttf
        - asset: assets/fonts/work_sans/WorkSans-MediumItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Regular.ttf
        - asset: assets/fonts/work_sans/WorkSans-SemiBold.ttf
        - asset: assets/fonts/work_sans/WorkSans-SemiBoldItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Thin.ttf
        - asset: assets/fonts/work_sans/WorkSans-ThinItalic.ttf
  assets:
    - assets/icons/
    - assets/old_icons/alarm/
    - assets/old_icons/app_devices/
    - assets/old_icons/automation/
    - assets/old_icons/big/
    - assets/old_icons/building_type/
    - assets/old_icons/color_presets/
    - assets/old_icons/controls/barrier/
    - assets/old_icons/controls/chargepoint/
    - assets/old_icons/controls/climate/
    - assets/old_icons/controls/door_lock/
    - assets/old_icons/controls/shading/
    - assets/old_icons/controls/siren/
    - assets/old_icons/device_alarm/
    - assets/old_icons/device_subtype/
    - assets/old_icons/device_type/
    - assets/old_icons/dogs/
    - assets/old_icons/energy_group/
    - assets/old_icons/energy_optimization_settings/
    - assets/old_icons/energy_statistics/
    - assets/old_icons/fh_font/
    - assets/old_icons/functionality/
    - assets/old_icons/household_settings/
    - assets/old_icons/hub/
    - assets/old_icons/mdu/battery/
    - assets/old_icons/mdu/contact/
    - assets/old_icons/mdu/device/
    - assets/old_icons/mdu/logo/
    - assets/old_icons/mdu/other/
    - assets/old_icons/mdu/premise/
    - assets/old_icons/mdu/ring/
    - assets/old_icons/mdu/role/
    - assets/old_icons/mdu/site/
    - assets/old_icons/mdu/stamp/
    - assets/old_icons/mdu/symbol/
    - assets/old_icons/media/
    - assets/old_icons/modes/
    - assets/old_icons/notification_group/
    - assets/old_icons/playground/
    - assets/old_icons/profile_settings/
    - assets/old_icons/room/
    - assets/old_icons/security/
    - assets/old_icons/services/
    - assets/old_icons/services/device_modes/
    - assets/old_icons/settings/
    - assets/old_icons/shading/
    - assets/old_icons/shared/
    - assets/old_icons/siren_mode/
    - assets/old_icons/square_flags/
    - assets/old_icons/text/
    - assets/old_icons/timeline/
    - assets/old_icons/timeline/events/
    - assets/old_icons/user_verification/
    - assets/old_icons/widgets/app_bar/
    - assets/old_icons/widgets/bottom_nav/
    - assets/old_icons/widgets/forms/fh_search/
    - assets/old_icons/widgets/pickers/fh_circular_color_temperature_picker/
    - assets/old_icons/widgets/pickers/fh_circular_picker/
    - assets/old_icons/widgets/pickers/fh_simple_slider/
    - assets/old_icons/widgets/sliders/
    - assets/old_icons/zwave_inclusion/