name: yggdrasil
description: Design system for Futurehome.
publish_to: none

version: 1.10.6

environment:
  sdk: ^3.2.0
  flutter: 3.16.0

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: 3.0.1
  intl: 0.18.1
  theme_tailor_annotation:
    git:
      ref: main
      url: git@github.com:futurehomeno/theme_tailor.git
      path: packages/theme_tailor_annotation
  flutter_svg: 2.0.9

dev_dependencies:
  # Run `flutter test --tags golden` to run all golden tests.
  # Run `flutter test --update-goldens` to regenerate goldens.
  alchemist: 0.7.0
  # Run `flutter pub run build_runner build --delete-conflicting-outputs` in order to generate stuff.
  build_runner: 2.4.6
  recase: 4.1.0
  intl_utils: 2.8.7
  flutter_test:
    sdk: flutter
  theme_tailor:
    git:
      ref: main
      url: git@github.com:futurehomeno/theme_tailor.git
      path: packages/theme_tailor

flutter_intl:
  enabled: true
  class_name: DefaultYggdrasilLocalizations
  main_locale: en
  arb_dir: l10n/generated
  output_dir: lib/src/generated
  use_deferred_loading: false

flutter:
  uses-material-design: true
  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/dosis/Dosis-Bold.ttf
        - asset: assets/fonts/dosis/Dosis-ExtraBold.ttf
        - asset: assets/fonts/dosis/Dosis-ExtraLight.ttf
        - asset: assets/fonts/dosis/Dosis-Light.ttf
        - asset: assets/fonts/dosis/Dosis-Medium.ttf
        - asset: assets/fonts/dosis/Dosis-Regular.ttf
        - asset: assets/fonts/dosis/Dosis-SemiBold.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
        - asset: assets/fonts/open_sans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/open_sans/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
        - asset: assets/fonts/open_sans/OpenSans-LightItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Medium.ttf
        - asset: assets/fonts/open_sans/OpenSans-MediumItalic.ttf
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/open_sans/OpenSans-SemiBoldItalic.ttf

    - family: WorkSans
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Black.ttf
        - asset: assets/fonts/work_sans/WorkSans-BlackItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Bold.ttf
        - asset: assets/fonts/work_sans/WorkSans-BoldItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraBold.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraLight.ttf
        - asset: assets/fonts/work_sans/WorkSans-ExtraLightItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Italic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Light.ttf
        - asset: assets/fonts/work_sans/WorkSans-LightItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Medium.ttf
        - asset: assets/fonts/work_sans/WorkSans-MediumItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Regular.ttf
        - asset: assets/fonts/work_sans/WorkSans-SemiBold.ttf
        - asset: assets/fonts/work_sans/WorkSans-SemiBoldItalic.ttf
        - asset: assets/fonts/work_sans/WorkSans-Thin.ttf
        - asset: assets/fonts/work_sans/WorkSans-ThinItalic.ttf
  assets:
    - assets/icons/
