/// Class providing names of SVG icons as static const strings.
///
/// Generated by scripts/icon_builder.dart.
class YgIcons {
  YgIcons._();

  static const String search = 'assets/icons/search.svg';
  static const String eyeOpen = 'assets/icons/eye-open.svg';
  static const String alert = 'assets/icons/alert.svg';
  static const String rotate = 'assets/icons/rotate.svg';
  static const String caretDot = 'assets/icons/caret_dot.svg';
  static const String power = 'assets/icons/power.svg';
  static const String handle = 'assets/icons/handle.svg';
  static const String supportBubble = 'assets/icons/support-bubble.svg';
  static const String failed = 'assets/icons/failed.svg';
  static const String eyeClosed = 'assets/icons/eye-closed.svg';
  static const String increase = 'assets/icons/increase.svg';
  static const String arrowLeft = 'assets/icons/arrow_left.svg';
  static const String link = 'assets/icons/link.svg';
  static const String caretLeft = 'assets/icons/caret_left.svg';
  static const String caretRight = 'assets/icons/caret_right.svg';
  static const String arrowUp = 'assets/icons/arrow_up.svg';
  static const String decrease = 'assets/icons/decrease.svg';
  static const String bell = 'assets/icons/bell.svg';
  static const String stop = 'assets/icons/stop.svg';
  static const String arrowRight = 'assets/icons/arrow_right.svg';
  static const String support = 'assets/icons/support.svg';
  static const String plus = 'assets/icons/plus.svg';
  static const String check = 'assets/icons/check.svg';
  static const String warning = 'assets/icons/warning.svg';
  static const String bluetooth = 'assets/icons/bluetooth.svg';
  static const String lockOpen = 'assets/icons/lock_open.svg';
  static const String email = 'assets/icons/email.svg';
  static const String info = 'assets/icons/info.svg';
  static const String refresh = 'assets/icons/refresh.svg';
  static const String alertBubble = 'assets/icons/alert-bubble.svg';
  static const String caretDown = 'assets/icons/caret_down.svg';
  static const String arrowDown = 'assets/icons/arrow_down.svg';
  static const String play = 'assets/icons/play.svg';
  static const String notification = 'assets/icons/notification.svg';
  static const String tip = 'assets/icons/tip.svg';
  static const String more = 'assets/icons/more.svg';
  static const String trash = 'assets/icons/trash.svg';
  static const String manualBook = 'assets/icons/manual-book.svg';
  static const String sum = 'assets/icons/sum.svg';
  static const String forbidden = 'assets/icons/forbidden.svg';
  static const String success = 'assets/icons/success.svg';
  static const String call = 'assets/icons/call.svg';
  static const String lockClosed = 'assets/icons/lock_closed.svg';
  static const String calendar = 'assets/icons/calendar.svg';
  static const String cross = 'assets/icons/cross.svg';
  static const String error = 'assets/icons/error.svg';
  static const String pause = 'assets/icons/pause.svg';
  static const String caretUp = 'assets/icons/caret_up.svg';
  static const String powerDisabled = 'assets/icons/power-disabled.svg';
  static const String minus = 'assets/icons/minus.svg';
  static const String placeholder = 'assets/icons/placeholder.svg';
}
