/// Class providing names of SVG icons as static const strings.
///
/// Generated by scripts/icon_builder.dart.
class YgIcons {
  YgIcons._();

  static const String search = 'assets/icons/search.svg';
  static const String eyeOpen = 'assets/icons/eye-open.svg';
  static const String alert = 'assets/icons/alert.svg';
  static const String rotate = 'assets/icons/rotate.svg';
  static const String power = 'assets/icons/power.svg';
  static const String increase = 'assets/icons/increase.svg';
  static const String arrowLeft = 'assets/icons/arrow_left.svg';
  static const String link = 'assets/icons/link.svg';
  static const String caretLeft = 'assets/icons/caret_left.svg';
  static const String caretRight = 'assets/icons/caret_right.svg';
  static const String arrowUp = 'assets/icons/arrow_up.svg';
  static const String decrease = 'assets/icons/decrease.svg';
  static const String stop = 'assets/icons/stop.svg';
  static const String arrowRight = 'assets/icons/arrow_right.svg';
  static const String plus = 'assets/icons/plus.svg';
  static const String check = 'assets/icons/check.svg';
  static const String bluetooth = 'assets/icons/bluetooth.svg';
  static const String lockOpen = 'assets/icons/lock_open.svg';
  static const String info = 'assets/icons/info.svg';
  static const String refresh = 'assets/icons/refresh.svg';
  static const String caretDown = 'assets/icons/caret_down.svg';
  static const String arrowDown = 'assets/icons/arrow_down.svg';
  static const String play = 'assets/icons/play.svg';
  static const String more = 'assets/icons/more.svg';
  static const String sum = 'assets/icons/sum.svg';
  static const String forbidden = 'assets/icons/forbidden.svg';
  static const String lockClosed = 'assets/icons/lock_closed.svg';
  static const String cross = 'assets/icons/cross.svg';
  static const String error = 'assets/icons/error.svg';
  static const String pause = 'assets/icons/pause.svg';
  static const String caretUp = 'assets/icons/caret_up.svg';
  static const String powerDisabled = 'assets/icons/power-disabled.svg';
  static const String minus = 'assets/icons/minus.svg';
  static const String placeholder = 'assets/icons/placeholder.svg';
}
