/// Class providing names of SVG icons as static const strings.
///
/// Generated by scripts/icon_builder.dart.
class YgIcons {
  const YgIcons._();

  static const String access = 'assets/icons/access.svg';
  static const String accessGroup = 'assets/icons/access_group.svg';
  static const String accessLocked = 'assets/icons/access_locked.svg';
  static const String accessUnlocked = 'assets/icons/access_unlocked.svg';
  static const String addAutomation = 'assets/icons/add_automation.svg';
  static const String additional = 'assets/icons/additional.svg';
  static const String admin = 'assets/icons/admin.svg';
  static const String alert = 'assets/icons/alert.svg';
  static const String alertBubble = 'assets/icons/alert_bubble.svg';
  static const String anglePosition = 'assets/icons/angle_position.svg';
  static const String apartment = 'assets/icons/apartment.svg';
  static const String apartmentAlt = 'assets/icons/apartment_alt.svg';
  static const String appStore = 'assets/icons/app_store.svg';
  static const String appliance = 'assets/icons/appliance.svg';
  static const String arduino = 'assets/icons/arduino.svg';
  static const String areas = 'assets/icons/areas.svg';
  static const String arrowDown = 'assets/icons/arrow_down.svg';
  static const String arrowLeft = 'assets/icons/arrow_left.svg';
  static const String arrowRight = 'assets/icons/arrow_right.svg';
  static const String arrowUp = 'assets/icons/arrow_up.svg';
  static const String associations = 'assets/icons/associations.svg';
  static const String attic = 'assets/icons/attic.svg';
  static const String autoChange = 'assets/icons/auto_change.svg';
  static const String aux1 = 'assets/icons/aux1.svg';
  static const String away = 'assets/icons/away.svg';
  static const String axisX = 'assets/icons/axis_x.svg';
  static const String axisY = 'assets/icons/axis_y.svg';
  static const String axisZ = 'assets/icons/axis_z.svg';
  static const String backyard = 'assets/icons/backyard.svg';
  static const String basement = 'assets/icons/basement.svg';
  static const String bathroom = 'assets/icons/bathroom.svg';
  static const String battery = 'assets/icons/battery.svg';
  static const String bedroom = 'assets/icons/bedroom.svg';
  static const String bedroomGuest = 'assets/icons/bedroom_guest.svg';
  static const String bee = 'assets/icons/bee.svg';
  static const String bees = 'assets/icons/bees.svg';
  static const String bell = 'assets/icons/bell.svg';
  static const String birdcage = 'assets/icons/birdcage.svg';
  static const String bluetooth = 'assets/icons/bluetooth.svg';
  static const String boiler = 'assets/icons/boiler.svg';
  static const String bomb = 'assets/icons/bomb.svg';
  static const String burglary = 'assets/icons/burglary.svg';
  static const String cabin = 'assets/icons/cabin.svg';
  static const String calendar = 'assets/icons/calendar.svg';
  static const String calendarAdd = 'assets/icons/calendar_add.svg';
  static const String calendarEdit = 'assets/icons/calendar_edit.svg';
  static const String calendarPin = 'assets/icons/calendar_pin.svg';
  static const String call = 'assets/icons/call.svg';
  static const String camera = 'assets/icons/camera.svg';
  static const String cameraScan = 'assets/icons/camera_scan.svg';
  static const String capacity = 'assets/icons/capacity.svg';
  static const String carbonDioxide = 'assets/icons/carbon_dioxide.svg';
  static const String carbonMonoxide = 'assets/icons/carbon_monoxide.svg';
  static const String caretDown = 'assets/icons/caret_down.svg';
  static const String caretLeft = 'assets/icons/caret_left.svg';
  static const String caretRight = 'assets/icons/caret_right.svg';
  static const String caretUp = 'assets/icons/caret_up.svg';
  static const String cart = 'assets/icons/cart.svg';
  static const String charger = 'assets/icons/charger.svg';
  static const String chargerQuestion = 'assets/icons/charger_question.svg';
  static const String check = 'assets/icons/check.svg';
  static const String childRoom = 'assets/icons/child_room.svg';
  static const String circle = 'assets/icons/circle.svg';
  static const String circleDouble = 'assets/icons/circle_double.svg';
  static const String circuitBreaker = 'assets/icons/circuit_breaker.svg';
  static const String climate = 'assets/icons/climate.svg';
  static const String closet = 'assets/icons/closet.svg';
  static const String cloud = 'assets/icons/cloud.svg';
  static const String color = 'assets/icons/color.svg';
  static const String commonArea = 'assets/icons/common_area.svg';
  static const String controlRoom = 'assets/icons/control_room.svg';
  static const String copy = 'assets/icons/copy.svg';
  static const String corridor = 'assets/icons/corridor.svg';
  static const String coverRemove = 'assets/icons/cover_remove.svg';
  static const String cross = 'assets/icons/cross.svg';
  static const String dashboard = 'assets/icons/dashboard.svg';
  static const String dashboardNo = 'assets/icons/dashboard_no.svg';
  static const String decrease = 'assets/icons/decrease.svg';
  static const String deviceConnected = 'assets/icons/device_connected.svg';
  static const String deviceEvCharger = 'assets/icons/device_ev_charger.svg';
  static const String deviceHub = 'assets/icons/device_hub.svg';
  static const String deviceHubAlt = 'assets/icons/device_hub_alt.svg';
  static const String deviceQrcode = 'assets/icons/device_qrcode.svg';
  static const String deviceSync = 'assets/icons/device_sync.svg';
  static const String deviceTransfer = 'assets/icons/device_transfer.svg';
  static const String deviceUpdateFailed = 'assets/icons/device_update_failed.svg';
  static const String deviceUpdateSuccess = 'assets/icons/device_update_success.svg';
  static const String dialPeakOff = 'assets/icons/dial_peak_off.svg';
  static const String diningRoom = 'assets/icons/dining_room.svg';
  static const String direction = 'assets/icons/direction.svg';
  static const String donut = 'assets/icons/donut.svg';
  static const String doorClosed = 'assets/icons/door_closed.svg';
  static const String doorClosedUnlocked = 'assets/icons/door_closed_unlocked.svg';
  static const String doorLockClosed = 'assets/icons/door_lock_closed.svg';
  static const String doorLocked = 'assets/icons/door_locked.svg';
  static const String doorOpen = 'assets/icons/door_open.svg';
  static const String doorOpenUnlocked = 'assets/icons/door_open_unlocked.svg';
  static const String downstairs = 'assets/icons/downstairs.svg';
  static const String dracula = 'assets/icons/dracula.svg';
  static const String dry = 'assets/icons/dry.svg';
  static const String edit = 'assets/icons/edit.svg';
  static const String electricCar = 'assets/icons/electric_car.svg';
  static const String email = 'assets/icons/email.svg';
  static const String emergencyNo = 'assets/icons/emergency_no.svg';
  static const String energy = 'assets/icons/energy.svg';
  static const String energyBattery = 'assets/icons/energy_battery.svg';
  static const String energyGrid = 'assets/icons/energy_grid.svg';
  static const String energyMeter = 'assets/icons/energy_meter.svg';
  static const String energySolar = 'assets/icons/energy_solar.svg';
  static const String energyWind = 'assets/icons/energy_wind.svg';
  static const String error = 'assets/icons/error.svg';
  static const String export = 'assets/icons/export.svg';
  static const String eyeClosed = 'assets/icons/eye_closed.svg';
  static const String eyeOpen = 'assets/icons/eye_open.svg';
  static const String faceId = 'assets/icons/face_id.svg';
  static const String failed = 'assets/icons/failed.svg';
  static const String fan = 'assets/icons/fan.svg';
  static const String fanAlt = 'assets/icons/fan_alt.svg';
  static const String fanSmall = 'assets/icons/fan_small.svg';
  static const String feather = 'assets/icons/feather.svg';
  static const String filter = 'assets/icons/filter.svg';
  static const String fireOff = 'assets/icons/fire_off.svg';
  static const String fireOn = 'assets/icons/fire_on.svg';
  static const String fishBone = 'assets/icons/fish_bone.svg';
  static const String flames = 'assets/icons/flames.svg';
  static const String flex = 'assets/icons/flex.svg';
  static const String forbidden = 'assets/icons/forbidden.svg';
  static const String force = 'assets/icons/force.svg';
  static const String furnace = 'assets/icons/furnace.svg';
  static const String futurehome = 'assets/icons/futurehome.svg';
  static const String garage = 'assets/icons/garage.svg';
  static const String garageClosed = 'assets/icons/garage_closed.svg';
  static const String garageOpen = 'assets/icons/garage_open.svg';
  static const String gas = 'assets/icons/gas.svg';
  static const String gasMaskOff = 'assets/icons/gas_mask_off.svg';
  static const String gasMaskOn = 'assets/icons/gas_mask_on.svg';
  static const String gateClosed = 'assets/icons/gate_closed.svg';
  static const String gateClosedUnlocked = 'assets/icons/gate_closed_unlocked.svg';
  static const String gateLocked = 'assets/icons/gate_locked.svg';
  static const String gateOpen = 'assets/icons/gate_open.svg';
  static const String gateOpenUnlocked = 'assets/icons/gate_open_unlocked.svg';
  static const String gear = 'assets/icons/gear.svg';
  static const String general = 'assets/icons/general.svg';
  static const String grandfather = 'assets/icons/grandfather.svg';
  static const String hallway = 'assets/icons/hallway.svg';
  static const String han = 'assets/icons/han.svg';
  static const String handle = 'assets/icons/handle.svg';
  static const String health = 'assets/icons/health.svg';
  static const String heater = 'assets/icons/heater.svg';
  static const String history = 'assets/icons/history.svg';
  static const String homeAway = 'assets/icons/home_away.svg';
  static const String homeMorning = 'assets/icons/home_morning.svg';
  static const String homeNight = 'assets/icons/home_night.svg';
  static const String homeVacation = 'assets/icons/home_vacation.svg';
  static const String hourglassEmpty = 'assets/icons/hourglass_empty.svg';
  static const String hourglassFull = 'assets/icons/hourglass_full.svg';
  static const String house = 'assets/icons/house.svg';
  static const String humidity = 'assets/icons/humidity.svg';
  static const String humiditySmall = 'assets/icons/humidity_small.svg';
  static const String increase = 'assets/icons/increase.svg';
  static const String info = 'assets/icons/info.svg';
  static const String install = 'assets/icons/install.svg';
  static const String integration = 'assets/icons/integration.svg';
  static const String intercom = 'assets/icons/intercom.svg';
  static const String inverter = 'assets/icons/inverter.svg';
  static const String jar = 'assets/icons/jar.svg';
  static const String key = 'assets/icons/key.svg';
  static const String keytag = 'assets/icons/keytag.svg';
  static const String keytagPin = 'assets/icons/keytag_pin.svg';
  static const String khz = 'assets/icons/khz.svg';
  static const String kitchen = 'assets/icons/kitchen.svg';
  static const String laundry = 'assets/icons/laundry.svg';
  static const String leaf = 'assets/icons/leaf.svg';
  static const String leafDown = 'assets/icons/leaf_down.svg';
  static const String leafRefresh = 'assets/icons/leaf_refresh.svg';
  static const String leafUp = 'assets/icons/leaf_up.svg';
  static const String leafWater = 'assets/icons/leaf_water.svg';
  static const String leakWaterOff = 'assets/icons/leak_water_off.svg';
  static const String leakWaterOn = 'assets/icons/leak_water_on.svg';
  static const String lighting = 'assets/icons/lighting.svg';
  static const String link = 'assets/icons/link.svg';
  static const String lockClosed = 'assets/icons/lock_closed.svg';
  static const String lockOpen = 'assets/icons/lock_open.svg';
  static const String locked = 'assets/icons/locked.svg';
  static const String login = 'assets/icons/login.svg';
  static const String lounge = 'assets/icons/lounge.svg';
  static const String luminance = 'assets/icons/luminance.svg';
  static const String manualBook = 'assets/icons/manual_book.svg';
  static const String map = 'assets/icons/map.svg';
  static const String measure = 'assets/icons/measure.svg';
  static const String media = 'assets/icons/media.svg';
  static const String micOff = 'assets/icons/mic_off.svg';
  static const String micOn = 'assets/icons/mic_on.svg';
  static const String minus = 'assets/icons/minus.svg';
  static const String miscellaneousRoom = 'assets/icons/miscellaneous_room.svg';
  static const String missing = 'assets/icons/missing.svg';
  static const String modes = 'assets/icons/modes.svg';
  static const String moisture = 'assets/icons/moisture.svg';
  static const String moneyBag = 'assets/icons/money_bag.svg';
  static const String more = 'assets/icons/more.svg';
  static const String movementNothing = 'assets/icons/movement_nothing.svg';
  static const String movementPaws = 'assets/icons/movement_paws.svg';
  static const String movementPawsFilled = 'assets/icons/movement_paws_filled.svg';
  static const String multipleChannels = 'assets/icons/multiple_channels.svg';
  static const String nfc = 'assets/icons/nfc.svg';
  static const String night = 'assets/icons/night.svg';
  static const String noise = 'assets/icons/noise.svg';
  static const String nothing = 'assets/icons/nothing.svg';
  static const String notification = 'assets/icons/notification.svg';
  static const String notingDown = 'assets/icons/noting_down.svg';
  static const String office1 = 'assets/icons/office-1.svg';
  static const String office = 'assets/icons/office.svg';
  static const String oldMan = 'assets/icons/old_man.svg';
  static const String omega = 'assets/icons/omega.svg';
  static const String outdoors = 'assets/icons/outdoors.svg';
  static const String panda = 'assets/icons/panda.svg';
  static const String pause = 'assets/icons/pause.svg';
  static const String pig = 'assets/icons/pig.svg';
  static const String pin = 'assets/icons/pin.svg';
  static const String pinCode = 'assets/icons/pin_code.svg';
  static const String pingPong = 'assets/icons/ping_pong.svg';
  static const String placeholder = 'assets/icons/placeholder.svg';
  static const String planet = 'assets/icons/planet.svg';
  static const String plant = 'assets/icons/plant.svg';
  static const String play1 = 'assets/icons/play-1.svg';
  static const String play = 'assets/icons/play.svg';
  static const String playQuestion = 'assets/icons/play_question.svg';
  static const String playlist = 'assets/icons/playlist.svg';
  static const String plus = 'assets/icons/plus.svg';
  static const String power = 'assets/icons/power.svg';
  static const String powerDisabled = 'assets/icons/power_disabled.svg';
  static const String pressure = 'assets/icons/pressure.svg';
  static const String pressureAlt = 'assets/icons/pressure_alt.svg';
  static const String qrCode = 'assets/icons/qr_code.svg';
  static const String radio = 'assets/icons/radio.svg';
  static const String read = 'assets/icons/read.svg';
  static const String refresh = 'assets/icons/refresh.svg';
  static const String refreshAlt = 'assets/icons/refresh_alt.svg';
  static const String relax1 = 'assets/icons/relax-1.svg';
  static const String relax = 'assets/icons/relax.svg';
  static const String reload = 'assets/icons/reload.svg';
  static const String rental = 'assets/icons/rental.svg';
  static const String restart = 'assets/icons/restart.svg';
  static const String rgb = 'assets/icons/rgb.svg';
  static const String rocket = 'assets/icons/rocket.svg';
  static const String rotate = 'assets/icons/rotate.svg';
  static const String rotation = 'assets/icons/rotation.svg';
  static const String safety = 'assets/icons/safety.svg';
  static const String sea = 'assets/icons/sea.svg';
  static const String search = 'assets/icons/search.svg';
  static const String searchAlt = 'assets/icons/search_alt.svg';
  static const String securityKey = 'assets/icons/security_key.svg';
  static const String seismic = 'assets/icons/seismic.svg';
  static const String sensor = 'assets/icons/sensor.svg';
  static const String settings = 'assets/icons/settings.svg';
  static const String shading = 'assets/icons/shading.svg';
  static const String shading0Percent = 'assets/icons/shading_0_percent.svg';
  static const String shading100Percent = 'assets/icons/shading_100_percent.svg';
  static const String shading25Percent = 'assets/icons/shading_25_percent.svg';
  static const String shading50Percent = 'assets/icons/shading_50_percent.svg';
  static const String shading75Percent = 'assets/icons/shading_75_percent.svg';
  static const String shaking = 'assets/icons/shaking.svg';
  static const String shutterBoth = 'assets/icons/shutter_both.svg';
  static const String shutterDown = 'assets/icons/shutter_down.svg';
  static const String shutterUp = 'assets/icons/shutter_up.svg';
  static const String sirenOff = 'assets/icons/siren_off.svg';
  static const String sirenSettings = 'assets/icons/siren_settings.svg';
  static const String smoke = 'assets/icons/smoke.svg';
  static const String smokeDisabled = 'assets/icons/smoke_disabled.svg';
  static const String smokeGasTest = 'assets/icons/smoke_gas_test.svg';
  static const String smokeHealth = 'assets/icons/smoke_health.svg';
  static const String smokeOn = 'assets/icons/smoke_on.svg';
  static const String smokeSensitive = 'assets/icons/smoke_sensitive.svg';
  static const String smokeTest = 'assets/icons/smoke_test.svg';
  static const String snowflake = 'assets/icons/snowflake.svg';
  static const String solar = 'assets/icons/solar.svg';
  static const String speed = 'assets/icons/speed.svg';
  static const String spider = 'assets/icons/spider.svg';
  static const String stairs = 'assets/icons/stairs.svg';
  static const String statistics = 'assets/icons/statistics.svg';
  static const String stop = 'assets/icons/stop.svg';
  static const String stopSmall = 'assets/icons/stop_small.svg';
  static const String stopwatch = 'assets/icons/stopwatch.svg';
  static const String storage = 'assets/icons/storage.svg';
  static const String success = 'assets/icons/success.svg';
  static const String sum = 'assets/icons/sum.svg';
  static const String support = 'assets/icons/support.svg';
  static const String supportBubble = 'assets/icons/support_bubble.svg';
  static const String switchButton = 'assets/icons/switch_button.svg';
  static const String tamperBad = 'assets/icons/tamper_bad.svg';
  static const String temperatureHigh = 'assets/icons/temperature_high.svg';
  static const String temperatureLow = 'assets/icons/temperature_low.svg';
  static const String temporaryPin = 'assets/icons/temporary_pin.svg';
  static const String threshold = 'assets/icons/threshold.svg';
  static const String tide = 'assets/icons/tide.svg';
  static const String timeline = 'assets/icons/timeline.svg';
  static const String toilet = 'assets/icons/toilet.svg';
  static const String touch = 'assets/icons/touch.svg';
  static const String touchId = 'assets/icons/touch_id.svg';
  static const String trash = 'assets/icons/trash.svg';
  static const String tree = 'assets/icons/tree.svg';
  static const String triggers = 'assets/icons/triggers.svg';
  static const String tropical = 'assets/icons/tropical.svg';
  static const String trumpet = 'assets/icons/trumpet.svg';
  static const String tv = 'assets/icons/tv.svg';
  static const String ultravioletUv = 'assets/icons/ultraviolet_uv.svg';
  static const String unlocked = 'assets/icons/unlocked.svg';
  static const String upstairs = 'assets/icons/upstairs.svg';
  static const String valves = 'assets/icons/valves.svg';
  static const String wallet = 'assets/icons/wallet.svg';
  static const String warning = 'assets/icons/warning.svg';
  static const String water = 'assets/icons/water.svg';
  static const String waterFlow = 'assets/icons/water_flow.svg';
  static const String waterPressure = 'assets/icons/water_pressure.svg';
  static const String watts = 'assets/icons/watts.svg';
  static const String weight = 'assets/icons/weight.svg';
  static const String wifiExcellent = 'assets/icons/wifi_excellent.svg';
  static const String wifiNoSignal = 'assets/icons/wifi_no_signal.svg';
  static const String wifiOk = 'assets/icons/wifi_ok.svg';
  static const String wifiUnknown = 'assets/icons/wifi_unknown.svg';
  static const String wifiWeak = 'assets/icons/wifi_weak.svg';
  static const String windowClosed = 'assets/icons/window_closed.svg';
  static const String windowClosedUnlocked = 'assets/icons/window_closed_unlocked.svg';
  static const String windowLocked = 'assets/icons/window_locked.svg';
  static const String windowLockedAlt = 'assets/icons/window_locked_alt.svg';
  static const String windowOpen = 'assets/icons/window_open.svg';
  static const String windowOpenAlt = 'assets/icons/window_open_alt.svg';
  static const String windowOpenUnlocked = 'assets/icons/window_open_unlocked.svg';
  static const String work = 'assets/icons/work.svg';
  static const String zigbee = 'assets/icons/zigbee.svg';
  static const String zwave = 'assets/icons/zwave.svg';

  static const List<Map<String, String>> allIcons = <Map<String, String>>[
    <String, String>{'access': access},
    <String, String>{'accessGroup': accessGroup},
    <String, String>{'accessLocked': accessLocked},
    <String, String>{'accessUnlocked': accessUnlocked},
    <String, String>{'addAutomation': addAutomation},
    <String, String>{'additional': additional},
    <String, String>{'admin': admin},
    <String, String>{'alert': alert},
    <String, String>{'alertBubble': alertBubble},
    <String, String>{'anglePosition': anglePosition},
    <String, String>{'apartment': apartment},
    <String, String>{'apartmentAlt': apartmentAlt},
    <String, String>{'appStore': appStore},
    <String, String>{'appliance': appliance},
    <String, String>{'arduino': arduino},
    <String, String>{'areas': areas},
    <String, String>{'arrowDown': arrowDown},
    <String, String>{'arrowLeft': arrowLeft},
    <String, String>{'arrowRight': arrowRight},
    <String, String>{'arrowUp': arrowUp},
    <String, String>{'associations': associations},
    <String, String>{'attic': attic},
    <String, String>{'autoChange': autoChange},
    <String, String>{'aux1': aux1},
    <String, String>{'away': away},
    <String, String>{'axisX': axisX},
    <String, String>{'axisY': axisY},
    <String, String>{'axisZ': axisZ},
    <String, String>{'backyard': backyard},
    <String, String>{'basement': basement},
    <String, String>{'bathroom': bathroom},
    <String, String>{'battery': battery},
    <String, String>{'bedroom': bedroom},
    <String, String>{'bedroomGuest': bedroomGuest},
    <String, String>{'bee': bee},
    <String, String>{'bees': bees},
    <String, String>{'bell': bell},
    <String, String>{'birdcage': birdcage},
    <String, String>{'bluetooth': bluetooth},
    <String, String>{'boiler': boiler},
    <String, String>{'bomb': bomb},
    <String, String>{'burglary': burglary},
    <String, String>{'cabin': cabin},
    <String, String>{'calendar': calendar},
    <String, String>{'calendarAdd': calendarAdd},
    <String, String>{'calendarEdit': calendarEdit},
    <String, String>{'calendarPin': calendarPin},
    <String, String>{'call': call},
    <String, String>{'camera': camera},
    <String, String>{'cameraScan': cameraScan},
    <String, String>{'capacity': capacity},
    <String, String>{'carbonDioxide': carbonDioxide},
    <String, String>{'carbonMonoxide': carbonMonoxide},
    <String, String>{'caretDown': caretDown},
    <String, String>{'caretLeft': caretLeft},
    <String, String>{'caretRight': caretRight},
    <String, String>{'caretUp': caretUp},
    <String, String>{'cart': cart},
    <String, String>{'charger': charger},
    <String, String>{'chargerQuestion': chargerQuestion},
    <String, String>{'check': check},
    <String, String>{'childRoom': childRoom},
    <String, String>{'circle': circle},
    <String, String>{'circleDouble': circleDouble},
    <String, String>{'circuitBreaker': circuitBreaker},
    <String, String>{'climate': climate},
    <String, String>{'closet': closet},
    <String, String>{'cloud': cloud},
    <String, String>{'color': color},
    <String, String>{'commonArea': commonArea},
    <String, String>{'controlRoom': controlRoom},
    <String, String>{'copy': copy},
    <String, String>{'corridor': corridor},
    <String, String>{'coverRemove': coverRemove},
    <String, String>{'cross': cross},
    <String, String>{'dashboard': dashboard},
    <String, String>{'dashboardNo': dashboardNo},
    <String, String>{'decrease': decrease},
    <String, String>{'deviceConnected': deviceConnected},
    <String, String>{'deviceEvCharger': deviceEvCharger},
    <String, String>{'deviceHub': deviceHub},
    <String, String>{'deviceHubAlt': deviceHubAlt},
    <String, String>{'deviceQrcode': deviceQrcode},
    <String, String>{'deviceSync': deviceSync},
    <String, String>{'deviceTransfer': deviceTransfer},
    <String, String>{'deviceUpdateFailed': deviceUpdateFailed},
    <String, String>{'deviceUpdateSuccess': deviceUpdateSuccess},
    <String, String>{'dialPeakOff': dialPeakOff},
    <String, String>{'diningRoom': diningRoom},
    <String, String>{'direction': direction},
    <String, String>{'donut': donut},
    <String, String>{'doorClosed': doorClosed},
    <String, String>{'doorClosedUnlocked': doorClosedUnlocked},
    <String, String>{'doorLockClosed': doorLockClosed},
    <String, String>{'doorLocked': doorLocked},
    <String, String>{'doorOpen': doorOpen},
    <String, String>{'doorOpenUnlocked': doorOpenUnlocked},
    <String, String>{'downstairs': downstairs},
    <String, String>{'dracula': dracula},
    <String, String>{'dry': dry},
    <String, String>{'edit': edit},
    <String, String>{'electricCar': electricCar},
    <String, String>{'email': email},
    <String, String>{'emergencyNo': emergencyNo},
    <String, String>{'energy': energy},
    <String, String>{'energyBattery': energyBattery},
    <String, String>{'energyGrid': energyGrid},
    <String, String>{'energyMeter': energyMeter},
    <String, String>{'energySolar': energySolar},
    <String, String>{'energyWind': energyWind},
    <String, String>{'error': error},
    <String, String>{'export': export},
    <String, String>{'eyeClosed': eyeClosed},
    <String, String>{'eyeOpen': eyeOpen},
    <String, String>{'faceId': faceId},
    <String, String>{'failed': failed},
    <String, String>{'fan': fan},
    <String, String>{'fanAlt': fanAlt},
    <String, String>{'fanSmall': fanSmall},
    <String, String>{'feather': feather},
    <String, String>{'filter': filter},
    <String, String>{'fireOff': fireOff},
    <String, String>{'fireOn': fireOn},
    <String, String>{'fishBone': fishBone},
    <String, String>{'flames': flames},
    <String, String>{'flex': flex},
    <String, String>{'forbidden': forbidden},
    <String, String>{'force': force},
    <String, String>{'furnace': furnace},
    <String, String>{'futurehome': futurehome},
    <String, String>{'garage': garage},
    <String, String>{'garageClosed': garageClosed},
    <String, String>{'garageOpen': garageOpen},
    <String, String>{'gas': gas},
    <String, String>{'gasMaskOff': gasMaskOff},
    <String, String>{'gasMaskOn': gasMaskOn},
    <String, String>{'gateClosed': gateClosed},
    <String, String>{'gateClosedUnlocked': gateClosedUnlocked},
    <String, String>{'gateLocked': gateLocked},
    <String, String>{'gateOpen': gateOpen},
    <String, String>{'gateOpenUnlocked': gateOpenUnlocked},
    <String, String>{'gear': gear},
    <String, String>{'general': general},
    <String, String>{'grandfather': grandfather},
    <String, String>{'hallway': hallway},
    <String, String>{'han': han},
    <String, String>{'handle': handle},
    <String, String>{'health': health},
    <String, String>{'heater': heater},
    <String, String>{'history': history},
    <String, String>{'homeAway': homeAway},
    <String, String>{'homeMorning': homeMorning},
    <String, String>{'homeNight': homeNight},
    <String, String>{'homeVacation': homeVacation},
    <String, String>{'hourglassEmpty': hourglassEmpty},
    <String, String>{'hourglassFull': hourglassFull},
    <String, String>{'house': house},
    <String, String>{'humidity': humidity},
    <String, String>{'humiditySmall': humiditySmall},
    <String, String>{'increase': increase},
    <String, String>{'info': info},
    <String, String>{'install': install},
    <String, String>{'integration': integration},
    <String, String>{'intercom': intercom},
    <String, String>{'inverter': inverter},
    <String, String>{'jar': jar},
    <String, String>{'key': key},
    <String, String>{'keytag': keytag},
    <String, String>{'keytagPin': keytagPin},
    <String, String>{'khz': khz},
    <String, String>{'kitchen': kitchen},
    <String, String>{'laundry': laundry},
    <String, String>{'leaf': leaf},
    <String, String>{'leafDown': leafDown},
    <String, String>{'leafRefresh': leafRefresh},
    <String, String>{'leafUp': leafUp},
    <String, String>{'leafWater': leafWater},
    <String, String>{'leakWaterOff': leakWaterOff},
    <String, String>{'leakWaterOn': leakWaterOn},
    <String, String>{'lighting': lighting},
    <String, String>{'link': link},
    <String, String>{'lockClosed': lockClosed},
    <String, String>{'lockOpen': lockOpen},
    <String, String>{'locked': locked},
    <String, String>{'login': login},
    <String, String>{'lounge': lounge},
    <String, String>{'luminance': luminance},
    <String, String>{'manualBook': manualBook},
    <String, String>{'map': map},
    <String, String>{'measure': measure},
    <String, String>{'media': media},
    <String, String>{'micOff': micOff},
    <String, String>{'micOn': micOn},
    <String, String>{'minus': minus},
    <String, String>{'miscellaneousRoom': miscellaneousRoom},
    <String, String>{'missing': missing},
    <String, String>{'modes': modes},
    <String, String>{'moisture': moisture},
    <String, String>{'moneyBag': moneyBag},
    <String, String>{'more': more},
    <String, String>{'movementNothing': movementNothing},
    <String, String>{'movementPaws': movementPaws},
    <String, String>{'movementPawsFilled': movementPawsFilled},
    <String, String>{'multipleChannels': multipleChannels},
    <String, String>{'nfc': nfc},
    <String, String>{'night': night},
    <String, String>{'noise': noise},
    <String, String>{'nothing': nothing},
    <String, String>{'notification': notification},
    <String, String>{'notingDown': notingDown},
    <String, String>{'office1': office1},
    <String, String>{'office': office},
    <String, String>{'oldMan': oldMan},
    <String, String>{'omega': omega},
    <String, String>{'outdoors': outdoors},
    <String, String>{'panda': panda},
    <String, String>{'pause': pause},
    <String, String>{'pig': pig},
    <String, String>{'pin': pin},
    <String, String>{'pinCode': pinCode},
    <String, String>{'pingPong': pingPong},
    <String, String>{'placeholder': placeholder},
    <String, String>{'planet': planet},
    <String, String>{'plant': plant},
    <String, String>{'play1': play1},
    <String, String>{'play': play},
    <String, String>{'playQuestion': playQuestion},
    <String, String>{'playlist': playlist},
    <String, String>{'plus': plus},
    <String, String>{'power': power},
    <String, String>{'powerDisabled': powerDisabled},
    <String, String>{'pressure': pressure},
    <String, String>{'pressureAlt': pressureAlt},
    <String, String>{'qrCode': qrCode},
    <String, String>{'radio': radio},
    <String, String>{'read': read},
    <String, String>{'refresh': refresh},
    <String, String>{'refreshAlt': refreshAlt},
    <String, String>{'relax1': relax1},
    <String, String>{'relax': relax},
    <String, String>{'reload': reload},
    <String, String>{'rental': rental},
    <String, String>{'restart': restart},
    <String, String>{'rgb': rgb},
    <String, String>{'rocket': rocket},
    <String, String>{'rotate': rotate},
    <String, String>{'rotation': rotation},
    <String, String>{'safety': safety},
    <String, String>{'sea': sea},
    <String, String>{'search': search},
    <String, String>{'searchAlt': searchAlt},
    <String, String>{'securityKey': securityKey},
    <String, String>{'seismic': seismic},
    <String, String>{'sensor': sensor},
    <String, String>{'settings': settings},
    <String, String>{'shading': shading},
    <String, String>{'shading0Percent': shading0Percent},
    <String, String>{'shading100Percent': shading100Percent},
    <String, String>{'shading25Percent': shading25Percent},
    <String, String>{'shading50Percent': shading50Percent},
    <String, String>{'shading75Percent': shading75Percent},
    <String, String>{'shaking': shaking},
    <String, String>{'shutterBoth': shutterBoth},
    <String, String>{'shutterDown': shutterDown},
    <String, String>{'shutterUp': shutterUp},
    <String, String>{'sirenOff': sirenOff},
    <String, String>{'sirenSettings': sirenSettings},
    <String, String>{'smoke': smoke},
    <String, String>{'smokeDisabled': smokeDisabled},
    <String, String>{'smokeGasTest': smokeGasTest},
    <String, String>{'smokeHealth': smokeHealth},
    <String, String>{'smokeOn': smokeOn},
    <String, String>{'smokeSensitive': smokeSensitive},
    <String, String>{'smokeTest': smokeTest},
    <String, String>{'snowflake': snowflake},
    <String, String>{'solar': solar},
    <String, String>{'speed': speed},
    <String, String>{'spider': spider},
    <String, String>{'stairs': stairs},
    <String, String>{'statistics': statistics},
    <String, String>{'stop': stop},
    <String, String>{'stopSmall': stopSmall},
    <String, String>{'stopwatch': stopwatch},
    <String, String>{'storage': storage},
    <String, String>{'success': success},
    <String, String>{'sum': sum},
    <String, String>{'support': support},
    <String, String>{'supportBubble': supportBubble},
    <String, String>{'switchButton': switchButton},
    <String, String>{'tamperBad': tamperBad},
    <String, String>{'temperatureHigh': temperatureHigh},
    <String, String>{'temperatureLow': temperatureLow},
    <String, String>{'temporaryPin': temporaryPin},
    <String, String>{'threshold': threshold},
    <String, String>{'tide': tide},
    <String, String>{'timeline': timeline},
    <String, String>{'toilet': toilet},
    <String, String>{'touch': touch},
    <String, String>{'touchId': touchId},
    <String, String>{'trash': trash},
    <String, String>{'tree': tree},
    <String, String>{'triggers': triggers},
    <String, String>{'tropical': tropical},
    <String, String>{'trumpet': trumpet},
    <String, String>{'tv': tv},
    <String, String>{'ultravioletUv': ultravioletUv},
    <String, String>{'unlocked': unlocked},
    <String, String>{'upstairs': upstairs},
    <String, String>{'valves': valves},
    <String, String>{'wallet': wallet},
    <String, String>{'warning': warning},
    <String, String>{'water': water},
    <String, String>{'waterFlow': waterFlow},
    <String, String>{'waterPressure': waterPressure},
    <String, String>{'watts': watts},
    <String, String>{'weight': weight},
    <String, String>{'wifiExcellent': wifiExcellent},
    <String, String>{'wifiNoSignal': wifiNoSignal},
    <String, String>{'wifiOk': wifiOk},
    <String, String>{'wifiUnknown': wifiUnknown},
    <String, String>{'wifiWeak': wifiWeak},
    <String, String>{'windowClosed': windowClosed},
    <String, String>{'windowClosedUnlocked': windowClosedUnlocked},
    <String, String>{'windowLocked': windowLocked},
    <String, String>{'windowLockedAlt': windowLockedAlt},
    <String, String>{'windowOpen': windowOpen},
    <String, String>{'windowOpenAlt': windowOpenAlt},
    <String, String>{'windowOpenUnlocked': windowOpenUnlocked},
    <String, String>{'work': work},
    <String, String>{'zigbee': zigbee},
    <String, String>{'zwave': zwave},
  ];
}
