name: Bug Report
description: Something isn't working
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What's wrong?
      description: Describe the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to...
        2. Click...
        3. See error