name: Feature Request
description: Suggest something new
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: What do you want?
      description: Describe your feature request
    validations:
      required: true