name: yggdrasil_demo
description: A demo app for Yggdrasil.
publish_to: "none"

version: 1.12.10

environment:
  sdk: ^3.2.0
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter
  yggdrasil:
    path: ../yggdrasil
  get_it: 7.6.4
  # Don't update due to the flutter_bloc in other repose.
  provider: 5.0.0
  dotted_border: 2.1.0
  mockito: 5.4.4
  package_info_plus: 8.0.3
  shared_preferences: 2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
