import 'package:flutter/material.dart';
import 'package:yggdrasil/yggdrasil.dart';
import 'package:yggdrasil_demo/core/_core.dart';
import 'package:yggdrasil_demo/widgets/_widgets.dart';

class TagsScreen extends StatelessWidget {
  const TagsScreen({super.key});

  static const String routeName = 'TagsScreen';

  static PageRouteBuilder<Widget> route() {
    return YgRouteBuilder().fadeTransition(
      settings: const RouteSettings(name: routeName),
      screen: const TagsScreen(),
    );
  }

  @override
  Widget build(BuildContext context) {
    return YgScreen(
      componentName: 'Tag',
      componentDesc: 'Tags',
      supernovaLink: 'Link',
      child: Column(
        children: <Widget>[
          YgListTile(title: 'Normal dialog'),
          Column(
            children: <Widget>[
              YgTag(
                variant: YgTagVariant.neutral,
                size: YgTagSize.small,
                weight: YgTagWeight.weak,
                onPressed: () {},
                child: const Text('Small Weak'),
              ),
              YgTag(
                variant: YgTagVariant.neutral,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                child: const Text('Small Strong'),
              ),
              YgTag.leftIcon(
                variant: YgTagVariant.neutral,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Small Strong'),
              ),
              YgTag.rightIcon(
                variant: YgTagVariant.neutral,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Small Strong'),
              ),
              YgTag.doubleIcon(
                variant: YgTagVariant.neutral,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                leadingIcon: 'icon',
                trailingIcon: 'icon',
                child: const Text('Small Strong'),
              ),
              YgTag(
                variant: YgTagVariant.neutral,
                size: YgTagSize.medium,
                weight: YgTagWeight.weak,
                onPressed: () {},
                child: const Text('Medium Weak'),
              ),
              YgTag(
                variant: YgTagVariant.neutral,
                size: YgTagSize.medium,
                weight: YgTagWeight.strong,
                onPressed: () {},
                child: const Text('Medium Strong'),
              ),
              YgTag.leftIcon(
                variant: YgTagVariant.neutral,
                size: YgTagSize.medium,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Medium Strong'),
              ),
              YgTag.rightIcon(
                variant: YgTagVariant.neutral,
                size: YgTagSize.medium,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Medium Strong'),
              ),
            ],
          ),
          YgListTile(title: 'Informative dialog'),
          Column(
            children: <Widget>[
              YgTag(
                variant: YgTagVariant.informative,
                size: YgTagSize.small,
                weight: YgTagWeight.weak,
                onPressed: () {},
                child: const Text('Small Weak'),
              ),
              YgTag(
                variant: YgTagVariant.informative,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                child: const Text('Small Strong'),
              ),
              YgTag.leftIcon(
                variant: YgTagVariant.informative,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Small Strong'),
              ),
              YgTag.rightIcon(
                variant: YgTagVariant.informative,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Small Strong'),
              ),
              YgTag.doubleIcon(
                variant: YgTagVariant.informative,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                leadingIcon: 'icon',
                trailingIcon: 'icon',
                child: const Text('Small Strong'),
              ),
              YgTag(
                variant: YgTagVariant.informative,
                size: YgTagSize.medium,
                weight: YgTagWeight.weak,
                onPressed: () {},
                child: const Text('Medium Weak'),
              ),
              YgTag(
                variant: YgTagVariant.informative,
                size: YgTagSize.medium,
                weight: YgTagWeight.strong,
                onPressed: () {},
                child: const Text('Medium Strong'),
              ),
              YgTag.leftIcon(
                variant: YgTagVariant.informative,
                size: YgTagSize.medium,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Medium Strong'),
              ),
              YgTag.rightIcon(
                variant: YgTagVariant.informative,
                size: YgTagSize.medium,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Medium Strong'),
              ),
            ],
          ),
          YgListTile(title: 'Positive dialog'),
          Column(
            children: <Widget>[
              YgTag(
                variant: YgTagVariant.positive,
                size: YgTagSize.small,
                weight: YgTagWeight.weak,
                onPressed: () {},
                child: const Text('Small Weak'),
              ),
              YgTag(
                variant: YgTagVariant.positive,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                child: const Text('Small Strong'),
              ),
              YgTag.leftIcon(
                variant: YgTagVariant.positive,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Small Strong'),
              ),
              YgTag.rightIcon(
                variant: YgTagVariant.positive,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Small Strong'),
              ),
              YgTag.doubleIcon(
                variant: YgTagVariant.positive,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                leadingIcon: 'icon',
                trailingIcon: 'icon',
                child: const Text('Small Strong'),
              ),
              YgTag(
                variant: YgTagVariant.positive,
                size: YgTagSize.medium,
                weight: YgTagWeight.weak,
                onPressed: () {},
                child: const Text('Medium Weak'),
              ),
              YgTag(
                variant: YgTagVariant.positive,
                size: YgTagSize.medium,
                weight: YgTagWeight.strong,
                onPressed: () {},
                child: const Text('Medium Strong'),
              ),
              YgTag.leftIcon(
                variant: YgTagVariant.positive,
                size: YgTagSize.medium,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Medium Strong'),
              ),
              YgTag.rightIcon(
                variant: YgTagVariant.positive,
                size: YgTagSize.medium,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Medium Strong'),
              ),
            ],
          ),
          YgListTile(title: 'Warning dialog'),
          Column(
            children: <Widget>[
              YgTag(
                variant: YgTagVariant.warning,
                size: YgTagSize.small,
                weight: YgTagWeight.weak,
                onPressed: () {},
                child: const Text('Small Weak'),
              ),
              YgTag(
                variant: YgTagVariant.warning,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                child: const Text('Small Strong'),
              ),
              YgTag.leftIcon(
                variant: YgTagVariant.warning,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Small Strong'),
              ),
              YgTag.rightIcon(
                variant: YgTagVariant.warning,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Small Strong'),
              ),
              YgTag.doubleIcon(
                variant: YgTagVariant.warning,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                leadingIcon: 'icon',
                trailingIcon: 'icon',
                child: const Text('Small Strong'),
              ),
              YgTag(
                variant: YgTagVariant.warning,
                size: YgTagSize.medium,
                weight: YgTagWeight.weak,
                onPressed: () {},
                child: const Text('Medium Weak'),
              ),
              YgTag(
                variant: YgTagVariant.warning,
                size: YgTagSize.medium,
                weight: YgTagWeight.strong,
                onPressed: () {},
                child: const Text('Medium Strong'),
              ),
              YgTag.leftIcon(
                variant: YgTagVariant.warning,
                size: YgTagSize.medium,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Medium Strong'),
              ),
              YgTag.rightIcon(
                variant: YgTagVariant.warning,
                size: YgTagSize.medium,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Medium Strong'),
              ),
            ],
          ),
          YgListTile(title: 'Negative dialog'),
          Column(
            children: <Widget>[
              YgTag(
                variant: YgTagVariant.negative,
                size: YgTagSize.small,
                weight: YgTagWeight.weak,
                onPressed: () {},
                child: const Text('Small Weak'),
              ),
              YgTag(
                variant: YgTagVariant.negative,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                child: const Text('Small Strong'),
              ),
              YgTag.leftIcon(
                variant: YgTagVariant.negative,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Small Strong'),
              ),
              YgTag.rightIcon(
                variant: YgTagVariant.negative,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Small Strong'),
              ),
              YgTag.doubleIcon(
                variant: YgTagVariant.negative,
                size: YgTagSize.small,
                weight: YgTagWeight.strong,
                onPressed: () {},
                leadingIcon: 'icon',
                trailingIcon: 'icon',
                child: const Text('Small Strong'),
              ),
              YgTag(
                variant: YgTagVariant.negative,
                size: YgTagSize.medium,
                weight: YgTagWeight.weak,
                onPressed: () {},
                child: const Text('Medium Weak'),
              ),
              YgTag(
                variant: YgTagVariant.negative,
                size: YgTagSize.medium,
                weight: YgTagWeight.strong,
                onPressed: () {},
                child: const Text('Medium Strong'),
              ),
              YgTag.leftIcon(
                variant: YgTagVariant.negative,
                size: YgTagSize.medium,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Medium Strong'),
              ),
              YgTag.rightIcon(
                variant: YgTagVariant.negative,
                size: YgTagSize.medium,
                weight: YgTagWeight.strong,
                onPressed: () {},
                icon: 'icon',
                child: const Text('Medium Strong'),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
