import 'package:flutter/material.dart';
import 'package:yggdrasil/yggdrasil.dart';
import 'package:yggdrasil_demo/core/_core.dart';
import 'package:yggdrasil_demo/widgets/_widgets.dart';

class TagsScreen extends StatelessWidget {
  const TagsScreen({super.key});

  static const String routeName = 'TagsScreen';

  static PageRouteBuilder<Widget> route() {
    return YgRouteBuilder().fadeTransition(
      settings: const RouteSettings(name: routeName),
      screen: const TagsScreen(),
    );
  }

  @override
  Widget build(BuildContext context) {
    return YgScreen(
      componentName: 'Tag',
      componentDesc: 'Tags',
      supernovaLink: 'Link',
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          YgCard(
            title: 'NeutralTag',
            child: Column(
              children: <Widget>[
                YgTag(
                  variant: YgTagVariant.neutral,
                  size: YgTagSize.small,
                  impact: YgTagImpact.weak,
                  onPressed: () {},
                  child: const Text('Small Weak'),
                ),
                const SizedBox(height: 8.0),
                YgTag(
                  variant: YgTagVariant.neutral,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.leftIcon(
                  variant: YgTagVariant.neutral,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.rightIcon(
                  variant: YgTagVariant.neutral,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.doubleIcon(
                  variant: YgTagVariant.neutral,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  leadingIcon: const Placeholder(),
                  trailingIcon: const Placeholder(),
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag(
                  variant: YgTagVariant.neutral,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.weak,
                  onPressed: () {},
                  child: const Text('Medium Weak'),
                ),
                const SizedBox(height: 8.0),
                YgTag(
                  variant: YgTagVariant.neutral,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  child: const Text('Medium Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.leftIcon(
                  variant: YgTagVariant.neutral,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Medium Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.rightIcon(
                  variant: YgTagVariant.neutral,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Medium Strong'),
                ),
              ],
            ),
          ),
          YgCard(
            title: 'InformativeTag',
            child: Column(
              children: <Widget>[
                YgTag(
                  variant: YgTagVariant.informative,
                  size: YgTagSize.small,
                  impact: YgTagImpact.weak,
                  onPressed: () {},
                  child: const Text('Small Weak'),
                ),
                const SizedBox(height: 8.0),
                YgTag(
                  variant: YgTagVariant.informative,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.leftIcon(
                  variant: YgTagVariant.informative,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.rightIcon(
                  variant: YgTagVariant.informative,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.doubleIcon(
                  variant: YgTagVariant.informative,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  leadingIcon: const Placeholder(),
                  trailingIcon: const Placeholder(),
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag(
                  variant: YgTagVariant.informative,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.weak,
                  onPressed: () {},
                  child: const Text('Medium Weak'),
                ),
                const SizedBox(height: 8.0),
                YgTag(
                  variant: YgTagVariant.informative,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  child: const Text('Medium Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.leftIcon(
                  variant: YgTagVariant.informative,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Medium Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.rightIcon(
                  variant: YgTagVariant.informative,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Medium Strong'),
                ),
              ],
            ),
          ),
          YgCard(
            title: 'PositiveTag',
            child: Column(
              children: <Widget>[
                YgTag(
                  variant: YgTagVariant.positive,
                  size: YgTagSize.small,
                  impact: YgTagImpact.weak,
                  onPressed: () {},
                  child: const Text('Small Weak'),
                ),
                const SizedBox(height: 8.0),
                YgTag(
                  variant: YgTagVariant.positive,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.leftIcon(
                  variant: YgTagVariant.positive,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.rightIcon(
                  variant: YgTagVariant.positive,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.doubleIcon(
                  variant: YgTagVariant.positive,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  leadingIcon: const Placeholder(),
                  trailingIcon: const Placeholder(),
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag(
                  variant: YgTagVariant.positive,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.weak,
                  onPressed: () {},
                  child: const Text('Medium Weak'),
                ),
                const SizedBox(height: 8.0),
                YgTag(
                  variant: YgTagVariant.positive,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  child: const Text('Medium Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.leftIcon(
                  variant: YgTagVariant.positive,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Medium Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.rightIcon(
                  variant: YgTagVariant.positive,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Medium Strong'),
                ),
              ],
            ),
          ),
          YgCard(
            title: 'WarningTag',
            child: Column(
              children: <Widget>[
                YgTag(
                  variant: YgTagVariant.warning,
                  size: YgTagSize.small,
                  impact: YgTagImpact.weak,
                  onPressed: () {},
                  child: const Text('Small Weak'),
                ),
                const SizedBox(height: 8.0),
                YgTag(
                  variant: YgTagVariant.warning,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.leftIcon(
                  variant: YgTagVariant.warning,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.rightIcon(
                  variant: YgTagVariant.warning,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.doubleIcon(
                  variant: YgTagVariant.warning,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  leadingIcon: const Placeholder(),
                  trailingIcon: const Placeholder(),
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag(
                  variant: YgTagVariant.warning,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.weak,
                  onPressed: () {},
                  child: const Text('Medium Weak'),
                ),
                const SizedBox(height: 8.0),
                YgTag(
                  variant: YgTagVariant.warning,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  child: const Text('Medium Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.leftIcon(
                  variant: YgTagVariant.warning,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Medium Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.rightIcon(
                  variant: YgTagVariant.warning,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Medium Strong'),
                ),
              ],
            ),
          ),
          YgCard(
            title: 'NegativeTag',
            child: Column(
              children: <Widget>[
                YgTag(
                  variant: YgTagVariant.negative,
                  size: YgTagSize.small,
                  impact: YgTagImpact.weak,
                  onPressed: () {},
                  child: const Text('Small Weak'),
                ),
                const SizedBox(height: 8.0),
                YgTag(
                  variant: YgTagVariant.negative,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.leftIcon(
                  variant: YgTagVariant.negative,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.rightIcon(
                  variant: YgTagVariant.negative,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.doubleIcon(
                  variant: YgTagVariant.negative,
                  size: YgTagSize.small,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  leadingIcon: const Placeholder(),
                  trailingIcon: const Placeholder(),
                  child: const Text('Small Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag(
                  variant: YgTagVariant.negative,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.weak,
                  onPressed: () {},
                  child: const Text('Medium Weak'),
                ),
                const SizedBox(height: 8.0),
                YgTag(
                  variant: YgTagVariant.negative,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  child: const Text('Medium Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.leftIcon(
                  variant: YgTagVariant.negative,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Medium Strong'),
                ),
                const SizedBox(height: 8.0),
                YgTag.rightIcon(
                  variant: YgTagVariant.negative,
                  size: YgTagSize.medium,
                  impact: YgTagImpact.strong,
                  onPressed: () {},
                  icon: const Placeholder(),
                  child: const Text('Medium Strong'),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
